In [8]:
import torch
import numpy as np

In [9]:
torch.randn(2, 5)

tensor([[-0.0917,  1.2063,  1.2526, -0.4206, -0.8594],
        [-0.8389, -0.0420,  0.8865,  0.3197, -0.4832]])

In [32]:
np.array([np.random.randn(14)]).astype(np.uint8)

array([[  2,   0,   1,   0,   0,   0,   0,   0,   0,   0,   1, 255,   0,
        255]], dtype=uint8)

In [34]:
x = np.random.randn(4)
x

array([ 0.06978774,  2.31611253,  0.29624735, -1.28295869])

In [35]:
x.astype(np.uint8)

array([  0,   2,   0, 255], dtype=uint8)